-- phpMyAdmin SQL Dump
-- version 5.2.3
-- https://www.phpmyadmin.net/
--
-- Anamakine: 127.0.0.1:3306
-- Üretim Zamanı: 16 May 2026, 18:51:26
-- Sunucu sürümü: 8.4.7
-- PHP Sürümü: 8.3.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `yemek_sistemi`
--

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `kullanicilar`
--

DROP TABLE IF EXISTS `kullanicilar`;
CREATE TABLE IF NOT EXISTS `kullanicilar` (
  `id` int NOT NULL AUTO_INCREMENT,
  `kullanici_adi` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sifre` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `kullanici_adi` (`kullanici_adi`)
) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Tablo döküm verisi `kullanicilar`
--

INSERT INTO `kullanicilar` (`id`, `kullanici_adi`, `sifre`) VALUES
(5, 'ardaisler', '$2y$10$nP1yIUNV9WJWYvY19aTPBe51mlNiK2CukRFMCb5iwSkkGM0okgEf2'),
(4, 'batuhankaragozoglu', '$2y$10$ZPXeiB5zmcChRaF4b55V6.Nr5u8pX1C9U8LdrQTVoKU4z9SAve6Pu');

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `tarifler`
--

DROP TABLE IF EXISTS `tarifler`;
CREATE TABLE IF NOT EXISTS `tarifler` (
  `id` int NOT NULL AUTO_INCREMENT,
  `baslik` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `icerik` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `gorsel_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `yazar_id` int NOT NULL,
  `eklenme_tarihi` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `kategori` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `yazar_id` (`yazar_id`)
) ENGINE=MyISAM AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Tablo döküm verisi `tarifler`
--

INSERT INTO `tarifler` (`id`, `baslik`, `icerik`, `gorsel_url`, `yazar_id`, `eklenme_tarihi`, `kategori`) VALUES
(10, 'Pilav Üstü Tavuk', 'Öğrenci evlerinin vazgeçilmezi, sporcu mutfağının demirbaşı ve sokak lezzetlerinin tartışmasız lideri! Tane tane dökülen tereyağlı pilavın üzerinde, tam kıvamında haşlanmış ve ince ince didiklenmiş tavuk göğsü... Üzerine bolca serpilen karabiberle birleştiğinde ortaya çıkan o koku, insanı çocukluğundaki o meşhur seyyar arabaların önüne götürüyor. Hem bütçe dostu hem de tam bir \"protein deposu\" arayanlar için gerçek bir kurtarıcı.\r\n\r\nHaşlama: Tavuk göğsünü bol suda, içine bir miktar tuz atarak iyice yumuşayana kadar haşlayın. Tavuk piştiğinde suyunu süzüp kenara ayırın, etleri de elinizle ince ince didikleyin.\r\n\r\nKavurma: Yıkanmış ve süzülmüş pirinçleri; tereyağı ve çok az sıvı yağ eklediğiniz tencerede pirinçler şeffaflaşana kadar 2-3 dakika kavurun.\r\n\r\nPişirme: Kavrulan pirinçlerin üzerine, ayırdığınız sıcak tavuk suyunu (1.5 katı ölçüsünde) ekleyin. Birkaç damla limon sıkarak (pirinçlerin beyaz kalması için) kapağı kapatın.\r\n\r\nDemleme: Pilav suyunu tamamen çekince altını kapatın. Üzerine kağıt havlu koyup en az 15 dakika demlenmeye bırakın.\r\n\r\nServis: Tabağa önce pilavı, üzerine didiklenmiş tavukları koyun. Bol karabiber eşliğinde sıcak servis yapın.', 'uploads/1778867598_tavukpilavv.jpg', 4, '2026-05-15 17:53:18', 'Ana Yemekler'),
(11, 'Mercimek Çorbası', 'Türk mutfağının tartışmasız en sevilen başlangıcı olan süzme mercimek çorbası, hem mideyi yormayan yapısıyla hem de yüksek besin değeriyle her sofranın baş tacıdır. Özellikle kış aylarının vazgeçilmezi olan bu lezzet, doğru kıvamı ve üzerine gezdirilen kızgın tereyağlı sosuyla tam bir şifa deposudur. Lifli yapısı sayesinde uzun süre tok tutarken, pratik hazırlanışıyla da mutfaktaki en büyük kurtarıcıdır.\r\n\r\nHazırlık: 1 su bardağı kırmızı mercimeği bol suyla yıkayın. 1 adet soğanı, 1 adet havucu ve 1 adet patatesi küp küp doğrayın.\r\n\r\nKavurma: Tencereye az miktar sıvı yağ alıp soğanları pembeleşene kadar kavurun. Ardından havuç, patates ve mercimekleri ekleyip 2-3 dakika daha çevirin.\r\n\r\nPişirme: Üzerine 6 su bardağı sıcak su (varsa et/tavuk suyu daha iyi olur) ve tuz ekleyerek sebzeler tamamen yumuşayana kadar orta ateşte pişirin.\r\n\r\nPürüzsüz Kıvam: Pişen çorbayı blenderdan geçirerek tamamen pürüzsüz bir kıvam almasını sağlayın. Kıvamı çok koyu gelirse biraz sıcak su ekleyerek açabilirsiniz.\r\n\r\nServis: Sos tavasında tereyağı ve pul biberi kızdırıp kaselerin üzerine gezdirin. Yanında bir dilim limonla servis yapın.', 'uploads/1778867816_mercimek.webp', 4, '2026-05-15 17:56:56', 'Ana Yemekler'),
(12, 'Sütlaç', 'Sütlü tatlıların tartışmasız kralı olan sütlaç, Türk mutfağının en köklü ve en sevilen tatlarından biridir. Az malzemeyle harikalar yaratan bu lezzet, pirincin sütle ağır ağır pişerek mükemmel bir kıvam almasıyla oluşur. Hem mideyi yormayan hafif yapısıyla hem de soğuk servis edildiğinde sunduğu ferahlıkla akşam yemeklerinin en zarif finalidir. Üzerine serpilen tarçınla birleştiğinde ortaya çıkan o koku, tam bir klasik öğrenci evi nostaljisidir.\r\n\r\nHazırlık: 1 çay bardağı pirinci güzelce yıkayın ve 2 su bardağı suyla, pirinçler iyice yumuşayıp suyunu çekene kadar haşlayın.\r\n\r\nBirleştirme: Haşlanan pirinçlerin üzerine 1 litre sütü ekleyin ve kaynamaya bırakın. Süt kaynamaya başladığında 1 su bardağı toz şekeri ilave edin.\r\n\r\nBağlama: Bir kasede 2 yemek kaşığı nişastayı yarım çay bardağı sütle açın. Bu karışımı tencereye azar azar ve sürekli karıştırarak ekleyin.\r\n\r\nPişirme: Sütlaç koyulaşmaya başladığında (yaklaşık 10-15 dakika) bir paket vanilya ekleyip karıştırın ve bir taşım daha kaynatıp altını kapatın.\r\n\r\nServis: Sıcakken kaselere paylaştırın. Oda sıcaklığına geldiğinde buzdolabına kaldırın. Servis ederken üzerine bolca tarçın serpmeyi unutmayın.', 'uploads/1778868041_sutlac.jpg', 4, '2026-05-15 18:00:41', 'Tatlılar'),
(13, 'Şalgam', 'Özellikle Adana ve çevresinin dünya mutfağına armağanı olan şalgam suyu; siyah havuç, şalgam turpu ve mayalanmış bulgur ununun muhteşem birleşimidir. Fermente bir içecek olduğu için tam bir probiyotik deposudur ve sindirimi kolaylaştırıcı özelliğiyle bilinir. Keskin, ekşi ve iştah açıcı tadıyla sadece bir içecek değil, aynı zamanda sofraların en güçlü eşlikçisidir. Soğuk servis edilen, acılı veya acısız seçenekleriyle her damak tadına hitap eden doğal bir şifa kaynağıdır.\r\n\r\nHazırlık: 1 kilogram siyah havucu ve 1 adet büyük boy şalgam turpunu soyun. Havuçları boyuna 4-5 parçaya, turpu ise elma dilimi şeklinde doğrayın.\r\n\r\nMayalama: Bir tülbentin içine 1 çay bardağı kadar düğü (ince bulgur) veya bir parça ekşi maya koyup bağlayın. Bunu 5 litrelik cam kavanozun dibine yerleştirin.\r\n\r\nDizme: Kavanozun içine doğradığınız havuç ve turpları doldurun. Üzerine 1 tatlı kaşığı limon tuzu ve 2.5 yemek kaşığı kaya tuzu ekleyin.\r\n\r\nDoldurma: Kavanozu ağzına kadar içme suyu ile doldurun. Eğer acılı istiyorsanız içine birkaç tane kuru süs biberi atabilirsiniz.\r\n\r\nBekleme: Kavanozun ağzını sıkıca kapatın. Oda sıcaklığında, güneş görmeyen bir yerde yaklaşık 15-20 gün fermente olmaya bırakın.\r\n\r\nServis: Süre sonunda tülbentteki mayayı içinden çıkarın. Şalgamı süzüp şişelere doldurarak buzdolabında soğutun. İçindeki havuçları (\"tane\" olarak bilinir) servis esnasında bardağa koymayı unutmayın.', 'uploads/1778869780_salgamm.jpg', 4, '2026-05-15 18:05:00', 'İçecekler'),
(14, 'Peynirli Poğaça', 'Kahvaltılarda ve ara öğünlerde tüketilmek üzere hazırlanan, maya bekleme süresi olmadığı için oldukça pratik bir şekilde hazırlanan hamur işidir. Kıyır kıyır dokusu ve doyurucu içeriğiyle ev yapımı atıştırmalıklar arasında yer alır. İç harcında kullanılan beyaz peynir ve üzerindeki çörek otu ile geleneksel bir lezzet sunar.\r\n\r\nHamur: 1 su bardağı yoğurt, 1 su bardağı sıvı yağ ve 2 yumurtayı (birinin sarısı üzerine) karıştırın. 1 paket kabartma tozu, 1 tatlı kaşığı tuz ve 3-4 su bardağı unu ekleyerek yumuşak bir hamur elde edin.\r\n\r\nİç Harç: Beyaz peyniri ezerek ince kıyılmış maydanozla karıştırın.\r\n\r\nHazırlanış: Hamurdan parçalar koparıp içine peynirli harcı yerleştirin ve kapatın.\r\n\r\nPişirme: Üzerine ayırdığınız yumurta sarısını sürün, susam/çörek otu serpin. 180°C fırında üzerleri kızarana kadar pişirin.', 'uploads/1778868715_pogaca.avif', 5, '2026-05-15 18:11:55', 'Hamur İşleri'),
(15, 'İzmir Köfte', 'Türk mutfağının fırın yemekleri arasında yer alan, köfte ve sebze kombinasyonundan oluşan geleneksel bir ana yemektir. Köfte harcı, elma dilim patates, biber ve domateslerin salçalı sos ile fırınlanması prensibine dayanır. Dengeli protein ve karbonhidrat içeriği sayesinde doyurucu bir öğün sunar.\r\n\r\nKöfte Hazırlığı: 500g kıyma, 1 adet rendelenmiş soğan, yarım demet maydanoz, yarım su bardağı galeta unu, 1 yumurta ve baharatları (tuz, karabiber, kimyon) yoğurup parmak şeklinde köfteler hazırlayın.\r\n\r\nSebzeler: 3-4 adet patatesi elma dilimi şeklinde doğrayın. Köfteleri ve patatesleri hafifçe yağda kızartın (bu işlem fırında dağılmasını engeller).\r\n\r\nDizilim: Bir fırın tepsisine patatesleri ve köfteleri sırayla dizin. Üzerine dilimlenmiş domates ve yeşil biberleri yerleştirin.\r\n\r\nSos: 1.5 yemek kaşığı domates salçasını 2 su bardağı sıcak su ve az miktar tuz ile açıp tepsinin üzerinde gezdirin.\r\n\r\nPişirme: Önceden ısıtılmış 200°C fırında, sebzeler tamamen yumuşayıp üzerleri kızarana kadar yaklaşık 30-35 dakika pişirin.', 'uploads/1778869208_izmirkofte.webp', 5, '2026-05-15 18:20:08', 'Ana Yemekler'),
(16, 'Magnolia Tatlısı', 'Amerikan mutfağı kökenli, sütlü puding ve bisküvi katmanlarından oluşan hafif bir tatlıdır. İçeriğindeki krema sayesinde pürüzsüz bir dokuya sahiptir. Taze meyvelerle desteklenen bu tatlı, genellikle porsiyonluk kaplarda veya cam kadehlerde katmanlı bir yapıda servis edilir.\r\n\r\nPuding Hazırlığı: 1 litre süt, 1 su bardağı toz şeker, 2 yemek kaşığı nişasta, 2 yemek kaşığı un ve 1 adet yumurta sarısını bir tencerede koyulaşana kadar karıştırarak pişirin.\r\n\r\nKrema Ekleme: Puding piştikten sonra altını kapatın, 1 paket vanilya ekleyip soğumaya bırakın. Tamamen soğuduktan sonra içine 1 paket (200ml) sıvı krema ekleyip mikserle pürüzsüz olana kadar çırpın.\r\n\r\nKatmanlar: 1 paket bebe bisküvisini veya yulaf bisküviyi rondodan geçirerek un haline getirin.\r\n\r\nBirleştirme: Servis kaplarının tabanına bir kaşık bisküvi koyun. Kabın kenarlarına ince dilimlenmiş muz veya çilekleri dizin. Üzerine pudingi ekleyin ve en üste tekrar bir kat bisküvi serpiştirin.\r\n\r\nServis: Buzdolabında en az 2-3 saat dinlendirdikten sonra soğuk olarak servis edin.', 'uploads/1778869626_magnoliaa.avif', 5, '2026-05-15 18:22:51', 'Tatlılar'),
(17, 'Brownie', 'Yoğun kakao ve çikolata içeriğine sahip, nemli ve yumuşak dokulu bir Amerikan mutfağı tatlısıdır. Klasik kek yapısından farklı olarak daha az un ve daha fazla yağ/şeker dengesiyle hazırlanır. Dışı ince ve çatlak bir kabuğa, içi ise sakızımsı bir kıvama sahiptir.\r\n\r\nHazırlık: 200g tereyağını eritin ve içine 200g bitter çikolatayı ekleyip karıştırarak erimesini sağlayın.\r\n\r\nÇırpma: 3 adet yumurtayı ve 1 su bardağı toz şekeri köpürene kadar çırpın. Hazırladığınız çikolatalı karışımı yavaşça ekleyin.\r\n\r\nKuru Malzemeler: Yarım su bardağı un, 3 yemek kaşığı kakao ve bir tutam tuzu eleyerek karışıma ekleyin. Spatula yardımıyla yavaşça karıştırın.\r\n\r\nPişirme: Karışımı yağlı kağıt serili kare bir fırın kabına boşaltın. 180°C fırında yaklaşık 20-25 dakika pişirin. (İçinin nemli kalması için fazla pişirmemeye dikkat edin).\r\n\r\nServis: Tamamen soğuduktan sonra dilimleyerek servis edin.\r\n', 'uploads/1778869549_brownie.jpg', 5, '2026-05-15 18:25:49', 'Tatlılar'),
(18, 'Patatesli Gözleme', 'Anadolu mutfağında yaygın olarak hazırlanan, mayasız hamurun ince açılarak içine harç konulması ve sac veya tavada pişirilmesi esasına dayanan bir hamur işidir. Hazırlanma süresinin kısalığı ve az malzeme gerektirmesi nedeniyle temel öğün veya atıştırmalık olarak tercih edilir.\r\n\r\nHamur: 3 su bardağı un, 1 tatlı kaşığı tuz ve yaklaşık 1 su bardağı suyu karıştırarak sert olmayan bir hamur yoğurun. Hamuru 15 dakika dinlendirin.\r\n\r\nİç Harç: 3 adet haşlanmış patatesi ezin. İçine ince kıyılmış 1 adet soğan, tuz, karabiber ve pul biber ekleyerek karıştırın.\r\n\r\nHazırlanış: Hamurdan bezeler koparıp un yardımıyla ince bir şekilde açın. Yarısına patatesli harcı yayın ve diğer yarısını üzerine kapatarak kenarlarına bastırın.\r\n\r\nPişirme: Yağsız tavada her iki yüzü de kızarana kadar pişirin. Pişen gözlemelerin üzerine sıcakken tereyağı sürün.', 'uploads/1778869925_gozleme.jpg', 4, '2026-05-15 18:32:05', 'Hamur İşleri'),
(19, 'Dereotlu Kurabiye', 'Pastane usulü olarak bilinen, kıyır dokusunu içeriğindeki sirke ve yağ oranından alan tuzlu bir hamur işidir. Dereotunun aromasıyla zenginleştirilen bu kurabiye, uzun süre tazeliğini koruma özelliğine sahiptir.\r\n\r\nHamur: 125g oda sıcaklığında tereyağı, yarım çay bardağı sıvı yağ, 1 adet yumurta (akı içine, sarısı üzerine), 1 yemek kaşığı sirke, 1 tatlı kaşığı şeker ve 1 çay kaşığı tuzu karıştırın.\r\n\r\nEkleme: Karışıma yarım demet ince kıyılmış dereotu ve 1 paket kabartma tozu ekleyin. Yaklaşık 3 su bardağı unu kontrollü ekleyerek yumuşak bir hamur elde edin.\r\n\r\nŞekil Verme: Hamurdan küçük parçalar koparıp yuvarlayın ve fırın tepsisine dizin.\r\n\r\nPişirme: Üzerlerine ayırdığınız yumurta sarısını sürün ve susam serpin. 180°C fırında yaklaşık 20-25 dakika, üzerleri kızarana kadar pişirin.', 'uploads/1778870043_dereotlu.jpg', 4, '2026-05-15 18:34:03', 'Hamur İşleri'),
(20, 'Limonata', 'Taze limon suyu, şeker ve suyun dengeli birleşimiyle hazırlanan, geleneksel bir soğuk içecektir. C vitamini açısından zengin, ferahlatıcı aromasıyla bilinen bu içecek, içeriğindeki limon kabuğu rendesi sayesinde yoğun meyve kokusuna sahiptir.\r\n\r\nHazırlık: 4 adet limonun kabuğunu rendenin ince tarafıyla rendeleyin (beyaz kısımlarını almamaya dikkat edin). Limonların suyunu sıkın.\r\n\r\nAromalandırma: Rendelediğiniz kabukları 1 su bardağı toz şeker ile birlikte, şeker tamamen nemlenene kadar elinizle ovun.\r\n\r\nBirleştirme: Hazırladığınız şekerli karışıma sıktığınız limon suyunu ekleyin ve şeker eriyene kadar karıştırın.\r\n\r\nSüzme: Üzerine 1.5 litre soğuk su ekleyin. Karışımı ince bir süzgeçten veya tülbentten geçirerek posalarından arındırın.\r\n\r\nServis: Taze nane yaprakları ve buz dilimleri ekleyerek soğuk servis edin.', 'uploads/1778870266_limonataaa.webp', 5, '2026-05-15 18:36:08', 'İçecekler'),
(21, 'Naneli Ayran', 'Yoğurdun su ve tuz ile çırpılmasıyla elde edilen geleneksel içeceğin, taze nane aromasıyla zenginleştirilmiş versiyonudur. Probiyotik içeriği ve elektrolit dengesini sağlama özelliğiyle bilinen, özellikle protein ağırlıklı ana yemeklerin yanında tercih edilen ferahlatıcı bir içecektir.\r\n\r\nKarışım: 2 su bardağı koyu kıvamlı yoğurdu bir sürahiye veya karıştırma kabına alın.\r\n\r\nÇırpma: İçine 1 çay kaşığı tuz ve 3 su bardağı soğuk su ekleyerek pürüzsüz bir kıvam alana kadar çırpın.\r\n\r\nAromalandırma: Yarım demet taze naneyi çok ince kıyın veya bir miktar suyla blenderdan geçirerek ayranın içine ekleyin.\r\n\r\nKöpürtme: İçeceğin üzerinde köpük oluşması için servis öncesi yüksek hızda çırpın veya çalkalayın.\r\n\r\nServis: Soğuk bardaklarda, üzerine bir adet taze nane yaprağı koyarak servis edin.', 'uploads/1778870328_naneliayran.png', 5, '2026-05-15 18:38:48', 'İçecekler'),
(22, 'Menemen', 'Yumurta, domates ve yeşil biberin birleşimiyle hazırlanan, Türk mutfağının en temel kahvaltılıklarından biridir. Mevsim sebzeleriyle hazırlanan bu yemek, sebzelerin kendi suyunda pişmesiyle oluşan yoğun aroması ve doyuruculuğu nedeniyle tercih edilir.\r\n\r\nHazırlık: 3 adet yeşil biberi doğrayın. 3 adet orta boy domatesin kabuklarını soyup küp küp kesin.\r\n\r\nPişirme: Tavaya 2 yemek kaşığı sıvı yağ ve 1 yemek kaşığı tereyağı alıp biberleri yumuşayana kadar kavurun. Ardından doğranmış domatesleri ekleyin.\r\n\r\nYumuşatma: Domatesler suyunu çekip iyice yumuşayana kadar tencerenin kapağı kapalı şekilde pişirin. Tuz ve isteğe bağlı pul biber ekleyin.\r\n\r\nFinal: 3 adet yumurtayı domateslerin üzerine kırın. Yumurtaların sarısını hafifçe dağıtarak istediğiniz pişme derecesine gelene kadar bekleyin.', 'uploads/1778870451_menemen.avif', 5, '2026-05-15 18:40:51', 'Kahvaltılıklar'),
(23, 'Mıhlama (Kuymak)', 'Karadeniz mutfağına özgü, mısır unu, tereyağı ve özel peynir çeşitlerinin birleşmesiyle hazırlanan yüksek enerjili bir kahvaltılıktır. Peynirin eriyip uzayan dokusu ve mısır ununun tereyağı ile kavrulması sonucu oluşan karakteristik tadı ile bilinir.\r\n\r\nKavurma: 2 yemek kaşığı kaliteli tereyağını tavada eritin ve hafifçe yanana kadar kızdırın.\r\n\r\nMısır Unu: İçine 2 yemek kaşığı mısır unu ekleyerek unun rengi hafifçe dönene kadar kavurun.\r\n\r\nSu Ekleme: 1 su bardağı suyu ekleyin ve mısır unu suyu çekip koyulaşana kadar karıştırın.\r\n\r\nPeynir: İçine 1 kase kadar kolot peyniri veya telli peynir ekleyin. Peynir eriyip tereyağı üzerine çıkana kadar çok karıştırmadan kısık ateşte pişirin.', 'uploads/1778870896_mihlama.jpg', 5, '2026-05-15 18:42:27', 'Kahvaltılıklar'),
(24, 'Krep', 'Süt, yumurta ve un karışımının tavada ince bir tabaka halinde pişirilmesiyle elde edilen, Avrupa mutfağı kökenli bir hamur işidir. Hem tatlı hem de tuzlu malzemelerle tüketilmeye uygun, nötr bir tada ve yumuşak bir dokuya sahiptir.\r\n\r\nKarışım: 2 adet yumurta ve 2 su bardağı sütü bir kapta çırpın.\r\n\r\nToparlanma: Yarım çay kaşığı tuz ve yaklaşık 1.5 su bardağı unu ekleyerek topak kalmayacak şekilde pürüzsüz bir sıvı elde edin.\r\n\r\nPişirme: Yapışmaz tavayı hafifçe yağlayın ve orta ateşte ısıtın. Bir kepçe hamuru tavaya döküp hızlıca yayın.\r\n\r\nFinal: Üzeri göz göz olup altı kızarınca diğer tarafını çevirin. Her iki tarafı da pişince tavadan alın.', 'uploads/1778870778_krep.jpg', 4, '2026-05-15 18:46:18', 'Kahvaltılıklar');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
